global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: "sunlight"
    scrape_interval: 15s
    metrics_path: "/api/v2/metrics"
    static_configs:
      - targets: ["sunlight-api:8000"]
        labels:
          environment: "production"
          service: "sunlight"
